### ISSUE TITLE
Update Vuetify to latest version

### ISSUE THREAD

**Issue by rajagopalx** [tookit/vue-material-admin#16]
Can you please update vuetifty to 1.1.14 (latest stable version) ?

**Comment by tookit** [comment]
I will do that later,

**Comment by tookit** [comment]
there a lot of updates/changes in vuetify 1.2.2, it will cause some errors and break some styles.
I need spend some time to apply the changes.

**Comment by rajagopalx** [comment]
Thanks for your effort. We got many inspirations from ur design.

**Comment by j574144** [comment]
Hi.

Firstly I want to congrat for great product.

For other part, I have update to vuetify 1.2.4 and not breaking any style.

Please try update and check it.

**Comment by j574144** [comment]
As complement, maybe you need only update some deprecated things...

**Comment by tookit** [comment]
thx @j574144

**Comment by ReInventTheWheel** [comment]
Vuetify 1.5.1 is available now.
