### ISSUE TITLE
Vue Cli 3

### ISSUE THREAD

**Issue by fjbardelli** [tookit/vue-material-admin#18]
Is posible use the dashboard, with de vue cli 3, via vue add....

**Comment by tookit** [comment]
You mean, as a template?

**Comment by AntoninSlejska** [comment]
I suppose that vue-material-admin is based on [vue-webpack-boilerplate](https://github.com/vuejs-templates/webpack). The vue-webpack-boilerplate and other Vue templates are deprecated. All features from the vue-webpack-boilerplate are incorporated in Vue CLI 3 now.

It would be great to migrate the vue-material-admin to Vue CLI 3.

**Comment by tookit** [comment]
updated
