### ISSUE TITLE
Would you like to update vuefity to the new Version 1.3.4?

### ISSUE THREAD

**Issue by CHCP** [tookit/vue-material-admin#25]
Hi tookit,
  The latest vuetify version is 1.3.4,  would you like to update vuefity to the new Version?

**Comment by tookit** [comment]
I'm so busy in these days, I plan to upgrade vuetify to lastest version. But it wil trigger a lot of style changes, I need fix those issues.

**Comment by CHCP** [comment]
Good, We will wait. This project is very useful for us, thanks a lot.
