### ISSUE TITLE
npm run dev failed 

### ISSUE THREAD

**Issue by Prakashpaarthipan** [tookit/vue-material-admin#33]
....
...
 @ ./src/components/email/List.vue 1:0-83 10:2-8 11:2-17 30:4-35:6 30:67-35:5 32
:16-22 33:25-40
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/components/email/Reply.vue?vue&type=template&id=5bbe7137&

Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
|
> <v-container fluid fill-height class="pa-0 mail-reply" id="mailReply">
|   <v-layout column class="mail-reply--layout">
|     <v-toolbar flat fixed class="mail-reply--toolbar" app>

 @ ./src/components/email/Reply.vue 1:0-84 10:2-8 11:2-17 30:4-35:6 30:68-35:5 3
2:16-22 33:25-40
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/pages/ui/Colors.vue?vue&type=template&id=2fc45e17&

Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
|
> <v-container id="page-colors" fluid grid-list-xl>
|   <v-layout row wrap>
|       <v-flex class="mb-3" xs12>

 @ ./src/pages/ui/Colors.vue 1:0-85 11:2-8 12:2-17 31:4-36:6 31:69-36:5 33:16-22
 34:25-40
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/components/AppFab.vue?vue&type=template&id=23640754&

Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
|
> <v-fab-transition>
|   <v-btn fab="fab" small dark="dark" fixed="fixed" bottom="bottom" right="righ
t" color="red" v-scroll="onScroll" v-show="fab" @click="toTop">
|     <v-icon>keyboard_arrow_up</v-icon>

 @ ./src/components/AppFab.vue 1:0-85 10:2-8 11:2-17 30:4-35:6 30:69-35:5 32:16-
22 33:25-40
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/components/widgets/form/ShipmentForm.vue?vue&type=template&id=6
62a6d49&

Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
|
> <v-form v-model="valid">
|     <v-subheader class="pa-0 mt-3">CONTACT DETAIL</v-subheader>
|     <v-text-field

 @ ./src/components/widgets/form/ShipmentForm.vue 1:0-91 10:2-8 11:2-17 30:4-35:
6 30:75-35:5 32:16-22 33:25-40
 @ ./src/pages/form/BasicForms.vue?vue&type=script&lang=js&
 @ ./src/pages/form/BasicForms.vue
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/components/widgets/form/PaymentForm.vue?vue&type=template&id=30
cb06ef&scoped=true&

Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
|
> <v-form v-model="valid">
|   <v-subheader class="pa-0">Payment Method</v-subheader>
|   <div class="layout ma-0 row">

 @ ./src/components/widgets/form/PaymentForm.vue 1:0-102 11:2-8 12:2-17 31:4-36:
6 31:86-36:5 33:16-22 34:25-40
 @ ./src/pages/form/BasicForms.vue?vue&type=script&lang=js&
 @ ./src/pages/form/BasicForms.vue
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/components/PageHeader.vue?vue&type=template&id=ad84f3a8&

Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
|
> <v-layout row class="align-center layout px-4 pt-4 app--page-header">
|   <div class="page-header-left">
|     <h3 class="pr-3">{{title}}</h3>

 @ ./src/components/PageHeader.vue 1:0-89 10:2-8 11:2-17 30:4-35:6 30:73-35:5 32
:16-22 33:25-40
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/components/AppDrawer.vue?vue&type=template&id=45c1f172&

Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
|
> <v-navigation-drawer
|   id="appDrawer"
|   :mini-variant.sync="mini"

 @ ./src/components/AppDrawer.vue 1:0-88 11:2-8 12:2-17 31:4-36:6 31:72-36:5 33:
16-22 34:25-40
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/components/AppToolbar.vue?vue&type=template&id=5e36a16c&

Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
|
> <v-toolbar
|   color="primary"
|   fixed

 @ ./src/components/AppToolbar.vue 1:0-89 10:2-8 11:2-17 30:4-35:6 30:73-35:5 32
:16-22 33:25-40
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/components/chat/ChatMenu.vue?vue&type=template&id=4f775a24&

Module parse failed: Unexpected token (2:2)
You may need an appropriate loader to handle this file type.
|
>   <div class="theme--dark py-5 darken-1">
|     <div>
|       <v-btn icon large flat slot="activator">

 @ ./src/components/chat/ChatMenu.vue 1:0-87 11:2-8 12:2-17 31:4-36:6 31:71-36:5
 33:16-22 34:25-40
 @ ./src/components/chat/ChatLayout.vue?vue&type=script&lang=js&
 @ ./src/components/chat/ChatLayout.vue
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/pages/Error.vue?vue&type=style&index=0&id=e0e013d8&scoped=true&
lang=css&

Module parse failed: Unexpected token (30:3)
You may need an appropriate loader to handle this file type.
|
|
> h1 {
|   font-size: 150px;
|   line-height: 150px;

 @ ./src/pages/Error.vue 4:0-89
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/pages/Deny.vue?vue&type=style&index=0&id=a646d2a0&scoped=true&l
ang=css&

Module parse failed: Unexpected token (30:3)
You may need an appropriate loader to handle this file type.
|
|
> h1 {
|   font-size: 150px;
|   line-height: 150px;

 @ ./src/pages/Deny.vue 4:0-88
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/components/chat/ChatMenu.vue?vue&type=style&index=0&lang=stylus
&

Module parse failed: Unexpected token (33:0)
You may need an appropriate loader to handle this file type.
|
|
> .mini-tile
|   a.list__tile--active
|     background:hsla(0,0%,100%,.12)

 @ ./src/components/chat/ChatMenu.vue 4:0-71
 @ ./src/components/chat/ChatLayout.vue?vue&type=script&lang=js&
 @ ./src/components/chat/ChatLayout.vue
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/pages/ui/Button.vue?vue&type=style&index=0&lang=css&

Module parse failed: Unexpected token (388:0)
You may need an appropriate loader to handle this file type.
|
|
> .custom-loader {
|   animation: loader 1s infinite;
|   display: flex;

 @ ./src/pages/ui/Button.vue 4:0-66
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/pages/form/Editors.vue?vue&type=style&index=0&id=5523c33f&lang=
stylus&scoped=true&

Module parse failed: Unexpected token (46:0)
You may need an appropriate loader to handle this file type.
|
|
> .quill
|   height : 520px
|

 @ ./src/pages/form/Editors.vue 4:0-94
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/components/widgets/card/PostListCard.vue?vue&type=style&index=0
&id=07c7408d&scoped=true&lang=css&

Module parse failed: Unexpected token (78:0)
You may need an appropriate loader to handle this file type.
|
|
> .ft-200 {
|   font-weight: 200;
| }

 @ ./src/components/widgets/card/PostListCard.vue 4:0-96
 @ ./src/pages/Dashboard.vue?vue&type=script&lang=js&
 @ ./src/pages/Dashboard.vue
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

 error  in ./src/pages/ui/Icon.vue?vue&type=style&index=0&id=5b3e6860&scoped=tru
e&lang=css&

Module parse failed: Unexpected token (89:0)
You may need an appropriate loader to handle this file type.
|
|
> .demo-icons-list {
|     display: -webkit-box;
|     display: flex;

 @ ./src/pages/ui/Icon.vue 4:0-88
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-ser
ver.js ./src/main.js

**And this is my package.json**
{
  "name": "vue-material-admin",
  "version": "1.0.0",
  "description": "A Vue Material Admin Template",
  "author": "Micahel Wang <wangqiangshen@gmail.com>",
  "private": true,
  "scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "unit": "jest --config test/unit/jest.conf.js --coverage",
    "e2e": "node test/e2e/runner.js",
    "test": "npm run unit && npm run e2e",
    "lint": "eslint --ext .js,.vue src test/unit test/e2e/specs",
    "build": "node build/build.js"
  },
  "dependencies": {
    "@babel/preset-react": "^7.0.0",
    "font-awesome": "^4.7.0",
    "lint": "^1.1.2",
    "lodash.truncate": "^4.4.2",
    "nprogress": "^0.2.0",
    "quill": "^1.3.6",
    "vee-validate": "^2.1.4",
    "vue": "^2.5.21",
    "vue-fullcalendar": "^1.0.9",
    "vue-perfect-scrollbar": "^0.1.0",
    "vue-quill-editor": "^3.0.6",
    "vue-resize": "^0.4.4",
    "vue-router": "^3.0.2",
    "vuetify": "^1.3.14"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.2.3",
    "autoprefixer": "^9.4.3",
    "babel-eslint": "^10.0.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-jest": "^23.6.0",
    "babel-loader": "^7.1.5",
    "babel-plugin-dynamic-import-node": "^2.2.0",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-plugin-transform-vue-jsx": "^3.7.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.26.0",
    "chalk": "^2.4.1",
    "chromedriver": "^2.45.0",
    "copy-webpack-plugin": "^4.6.0",
    "cross-spawn": "^6.0.5",
    "css-loader": "^2.0.1",
    "eslint": "^5.10.0",
    "eslint-config-alloy": "^1.4.2",
    "eslint-config-standard": "^12.0.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^8.0.0",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^5.0.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "faker": "^4.1.0",
    "file-loader": "^2.0.0",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "fs-finder": "^1.8.1",
    "html-webpack-plugin": "^3.2.0",
    "jest": "^23.6.0",
    "jest-serializer-vue": "^2.0.2",
    "json-schema-faker": "^0.5.0-rc9",
    "json-server": "^0.14.0",
    "less-loader": "^4.1.0",
    "mime-types": "^2.1.21",
    "mockjs": "^1.0.1-beta3",
    "mockjs-webpack-plugin": "^1.0.0",
    "nightwatch": "^1.0.16",
    "node-dir": "^0.1.17",
    "node-notifier": "^5.3.0",
    "optimize-css-assets-webpack-plugin": "^5.0.1",
    "ora": "^3.0.0",
    "portfinder": "^1.0.20",
    "postcss-import": "^12.0.1",
    "postcss-loader": "^3.0.0",
    "postcss-url": "^8.0.0",
    "raw-loader": "^1.0.0",
    "rimraf": "^2.6.2",
    "selenium-server": "^3.141.59",
    "semver": "^5.6.0",
    "shelljs": "^0.8.3",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "uglifyjs-webpack-plugin": "^2.0.1",
    "url-loader": "^1.1.2",
    "vue-jest": "^3.0.2",
    "vue-loader": "^15.4.2",
    "vue-style-loader": "^4.1.2",
    "vue-template-compiler": "^2.5.21",
    "webpack": "^4.28.2",
    "webpack-bundle-analyzer": "^3.0.3",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10",
    "webpack-merge": "^4.1.5"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

help to solve this issue.

**Comment by tookit** [comment]
see the new updates,
