### ISSUE TITLE
The breadcrumb can't show normally on each page

### ISSUE THREAD

**Issue by ALLTAKENS** [tookit/vue-material-admin#36]
there is just a dash in the place where breadcrumb should showed without icon and path on each page

**Comment by zhovtyj** [comment]
Full code for component PageHeader (this is fast solution, js can be improved):
  <template>
  <v-layout row class="align-center layout px-4 pt-4 app--page-header">
    <v-breadcrumbs :items="breadcrumbs" divider=">"></v-breadcrumbs>
    <div class="page-header-left">
      <h3 class="pr-3">{{title}}</h3>
    </div>
    <v-spacer></v-spacer>
    <div class="page-header-right">
      <v-btn icon>
        <v-icon class="text--secondary">refresh</v-icon>
      </v-btn>
    </div>
  </v-layout>
</template>

  <script>

      export default {
          data() {
              return {
                  breadcrumbs: [],
                  title: 'Hello World'
              }
          },
          watch: {
              $route() {
                  this.getBreadcrumb()
              }
          },
          created() {
              this.getBreadcrumb()
          },
          methods: {
              getBreadcrumb() {
                  let matched = this.$route.matched.filter(item => item.name);
                  const first = matched[0];
                  if (first && first.name.trim().toLocaleLowerCase() !== 'Dashboard'.toLocaleLowerCase()) {
                      this.breadcrumbs.push({
                          text: 'Dashboard',
                          href: '/dashboard',
                          disabled: false,
                      });
                  }
                  matched.forEach(item => {
                      if (item && item.name.trim().toLocaleLowerCase() !== 'Dashboard'.toLocaleLowerCase()) {
                          let disabled = false;
                          if (item === matched[matched.length - 1]) {
                              this.title = item.meta.title;
                              disabled = true;
                          }
                          this.breadcrumbs.push({
                              text: item.meta.title,
                              href: item.path,
                              disabled: disabled,
                          });
                      }
                  });
              },
          }
      }
  </script>
