### ISSUE TITLE
ERROR in static/js/vendor.52742d45700d8b43d148.js from UglifyJs undefined

### ISSUE THREAD

**Issue by nazihheni** [tookit/vue-material-admin#41]
ERROR in static/js/vendor.52742d45700d8b43d148.js from UglifyJs
undefined

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-material-admin@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-material-admin@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v8.15.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vue-material-admin@1.0.0~prebuild: vue-material-admin@1.0.0
6 info lifecycle vue-material-admin@1.0.0~build: vue-material-admin@1.0.0
7 verbose lifecycle vue-material-admin@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle vue-material-admin@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\nazih\Desktop\Vue_test\mosalawebapp\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Users\nazih\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;;C:\Users\nazih\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\nazih\AppData\Roaming\npm
9 verbose lifecycle vue-material-admin@1.0.0~build: CWD: C:\Users\nazih\Desktop\Vue_test\mosalawebapp
10 silly lifecycle vue-material-admin@1.0.0~build: Args: [ '/d /s /c', 'node build/build.js' ]
11 silly lifecycle vue-material-admin@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle vue-material-admin@1.0.0~build: Failed to exec build script
13 verbose stack Error: vue-material-admin@1.0.0 build: `node build/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid vue-material-admin@1.0.0
15 verbose cwd C:\Users\nazih\Desktop\Vue_test\mosalawebapp
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error vue-material-admin@1.0.0 build: `node build/build.js`
22 error Exit status 1
23 error Failed at the vue-material-admin@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tookit** [comment]
my evn

- npm 6.50
- node 8.12

you can try upgrade your npm
