### ISSUE TITLE
Update Vuetify to latest version(1.5.5)

### ISSUE THREAD

**Issue by ReInventTheWheel** [tookit/vue-material-admin#42]
Now the latest version is 1.5.1 which introduced a lot of bug fixes and new features.

**Comment by CHCP** [comment]
We can wait for Vue 3.0 and Vuetify 2.0, they all support TypeScript.  haha.

**Comment by tookit** [comment]
it's a good idea. haha

**Comment by ReInventTheWheel** [comment]
Hi @tookit , do you have any plan to make any changes(not necessarily big ones) to the current codebase in the near future(maybe within one or two months)? I appreciate it if you can inform me of this information. Thank you.

**Comment by tookit** [comment]
@ReInventTheWheel , yes, I plan to do this in next month, because i'm so busy right now, and in fact I'm a backend developer

**Comment by ShawshankLin** [comment]
What's going on?
