### ISSUE TITLE
The breadcrumb isn't working properly

### ISSUE THREAD

**Issue by GabrielSchenato** [tookit/vue-material-admin#44]
Hi, the breadcrumb isn't working properly, and some things are different from the demo.
![capturar](https://user-images.githubusercontent.com/26235097/53526959-62607380-3ac4-11e9-8376-ce52fb0a534e.PNG)

**Comment by tookit** [comment]
breadcrumb？

**Comment by GabrielSchenato** [comment]
Yes from this component PageHeader.vue     <v-breadcrumbs divider="-" :items="breadcrumbs">, you can see in my picture

**Comment by GabrielSchenato** [comment]
Is not like yours
![captura de tela de 2019-02-28 11-35-02](https://user-images.githubusercontent.com/26235097/53573750-ee1de280-3b4c-11e9-8179-a95897be21fd.png)

**Comment by tookit** [comment]
I got it, I guess the your route trigger the issue

**Comment by GabrielSchenato** [comment]
but I cloned your project and did not modify anything and it did not work either. And some things are different from the demo here http://vma.isocked.com/#/dashboard

**Comment by GabrielSchenato** [comment]
Can you help me?

**Comment by mjsunny** [comment]
change 
`breadcrumbs.push(item.title); 
breadcrumbs.push(child.title);` 
to
`breadcrumbs.push({text: item.title});
breadcrumbs.push({text: child.title});`

**Comment by supermebing** [comment]
确实有问题  跟Demo展示的不一样

**Comment by GabrielSchenato** [comment]
Thanks @mjsunny, but I can't put a icon like the demo

**Comment by mjsunny** [comment]
If you want to put a icon then revert everything back to original PageHeader.vue file and then replace `<v-breadcrumbs>` tag to 
```
<v-breadcrumbs divider="-">
    <v-breadcrumbs-item><v-icon>home</v-icon></v-breadcrumbs-item>                               
    <v-breadcrumbs-item v-for="(breadcrumb, index) in breadcrumbs" :key="index">{{breadcrumbs[index]}}</v-breadcrumbs-item>
</v-breadcrumbs>
```

**Comment by GabrielSchenato** [comment]
Oh really thank you @mjsunny, I need to ask something, if you refresh the page in the route http://localhost:8000/#/login for exemple it's load the Dashboard first instead of the Login page after some seconds the Login page appears

**Comment by rizkyarlin** [comment]
> Oh really thank you @mjsunny, I need to ask something, if you refresh the page in the route http://localhost:8000/#/login for exemple it's load the Dashboard first instead of the Login page after some seconds the Login page appears

Set a timeout then call the router programmatically. https://router.vuejs.org/guide/essentials/navigation.html
