### ISSUE TITLE
checkbox, radio button and some icons is not show correctly 

### ISSUE THREAD

**Issue by letien524** [tookit/vue-material-admin#47]
![image](https://user-images.githubusercontent.com/14271723/54702791-22902780-4b6a-11e9-9230-15f39aa9a1fd.png)
![image](https://user-images.githubusercontent.com/14271723/54702817-30de4380-4b6a-11e9-9e31-44b38a5cde8a.png)
![image](https://user-images.githubusercontent.com/14271723/54702867-4a7f8b00-4b6a-11e9-854a-25412f94880b.png)
![image](https://user-images.githubusercontent.com/14271723/54702939-70a52b00-4b6a-11e9-8e35-aec8a65b241a.png)

**Comment by BearD01001** [comment]
same issue

**Comment by BearD01001** [comment]
![image](https://user-images.githubusercontent.com/16353144/55127797-421be700-514c-11e9-810b-63638e1c1f75.png)
Switch iconfont to material design
ref: [https://vuetifyjs.com/framework/icons](https://vuetifyjs.com/framework/icons)
