### ISSUE TITLE
How to add new font to the project?

### ISSUE THREAD

**Issue by RosilBelli** [tookit/vue-material-admin#5]
Hi!

I'm having trouble to add a new font to the project. My last attempt was placing them inside the static folder. I created a /static/css folder with the icon.css file and a /static/fonts folder with the ttf file there.
On the css I have the font face declaration as follows:

```
@font-face {
  font-family: "Flaticon";
  url("../fonts/Flaticon.ttf") format("truetype"),
  font-weight: normal;
  font-style: normal;
}
```

But when I try to use its classes inside the code nothing is shown and I realized that it seems that the ttf file is not being loaded on the generated code.

What am I doing wrong?
Really appreciate any help.

Thanks!

**Comment by tookit** [comment]
you can try absolute path in your css, then import the css in `main.js`
such as `import 'font-awesome/css/font-awesome.css';`

**Comment by RosilBelli** [comment]
I tried to do that also. 
Today I could make it work by adding the font-face declaration on the theme/default.styl file:
```
@font-face
  font-family Flaticon
  font-style normal
  src url(../../static/fonts/Flaticon.ttf) format("truetype")
```

Thanks!
