### ISSUE TITLE
about multi-label functions

### ISSUE THREAD

**Issue by yoyomule** [tookit/vue-material-admin#52]
Hello, are you still considering to continue to improve? For example, to enhance some multi-label functions, and to solve the problem that the iframe box will be refreshed when switching labels, this is still useful for a management system. Also included to improve some permissions and other issues, such as https://panjiachen.github.io/vue-element-admin/#/dashboard. Thank you.
![QQ截图20190513161655](https://user-images.githubusercontent.com/10000818/57606026-92cf8e00-759a-11e9-8f44-2940080620f5.png)

**Comment by tookit** [comment]
I will consider it
