### ISSUE TITLE
Module parse failed: Unexpected character ' ' (1:3)

### ISSUE THREAD

**Issue by scrapybott** [tookit/vue-material-admin#53]
ERROR  Failed to compile with 1 errors                                                                         22:44:41

 error  in ./node_modules/core-js/modules/es6.regexp.exec.js

Module parse failed: Unexpected character ' ' (1:3)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

 @ ./node_modules/core-js/modules/_fix-re-wks.js 2:0-28
 @ ./node_modules/core-js/modules/es6.regexp.split.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vuetify-loader/lib/loader.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/ui/Datepicker.vue?vue&type=script&lang=js&
 @ ./src/views/ui/Datepicker.vue?vue&type=script&lang=js&
 @ ./src/views/ui/Datepicker.vue
 @ ./src/router/paths.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.5.33.62:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by scrapybott** [comment]
i get this error when i type npm run server. am using node version 8.11.2 and npm 5.6.0

**Comment by albenik** [comment]
@scrapybott This project uses `yarn` as package manager.
Did you try `yarn run serve`?
