### ISSUE TITLE
the width of charts bar in dashboard beyonds v-flex width

### ISSUE THREAD

**Issue by abelit** [tookit/vue-material-admin#54]
When first enter the dashboard page or refresh dashboard page, the width of  echarts bar in dashboard will beyonds the parent v-flex dom's width. I have try some demo and the problem always exists. The real thing like this:

![screenshot-localhost-8081-2019 06 20-17-46-54](https://user-images.githubusercontent.com/10794056/59840422-d5c31500-9341-11e9-800c-d2509783d001.png)

**Comment by tookit** [comment]
what is your screen size?

**Comment by abelit** [comment]
1920x1080

**Comment by abelit** [comment]
> what is your screen size?

1920x1080

**Comment by hefujie1988** [comment]
me too

**Comment by hefujie1988** [comment]
what is your solution ?

**Comment by hefujie1988** [comment]
this.chartInstance.resize()
i add this in echart.js
