### ISSUE TITLE
Echart Vue Wrapper not reactive

### ISSUE THREAD

**Issue by mhimi1** [tookit/vue-material-admin#56]
The Echarts Vue Wrapper in echart.js is NOT reactive. Data changes do not update the chart(s) unless page is refreshed. 

Furthermore, if the chart has data and then, for example, a filter is applied that returns no data, the chart data will not be cleaned, so the chart will still show the old data instead of no data.

The above can be fixed by adding a watcher that watches pathOption and calls this.init() on data change (for data updates) and for clearing the data, it can call this.clean() after checking if the data is empty.

```
watch: {
    pathOption: function (data) {
      if (data[0][1].length < 1) {
        this.clean();    
      }
      this.init();
    }
}
```
I can submit a pull request once I get a bit more time.

**Comment by elshazer** [comment]
Thank youuuuuuuuu bro

**Comment by mhimi1** [comment]
You’re welcome!

**Comment by hefujie1988** [comment]
thank you very much, you really help me

**Comment by ricardo17coelho** [comment]
@mhimi1 thank you for this solution, it works.
But echarts show this warning : "`There is a chart instance already initialized on the dom`." (console) 
if have mutliple charts on the same page.
