### ISSUE TITLE
Fix header of v-data-table, scroll  v-data-table

### ISSUE THREAD

**Issue by luyentm** [tookit/vue-material-admin#57]
Thank you for your useful source code
 
Currently I would like to fix position of header, I have investigate that current vuetify are not supported, this feature will support in vuetify 2+.  [link](https://next.vuetifyjs.com/vi-VN/components/simple-tables)
Could you please upgrade vuetify to 2+. I have try it, but not sucessful.

Thank you.

**Comment by DeivyPereira** [comment]
Any progress here for the fixed header or for hidden colum???


Algún avance aquí para el fixed header o para hidden colum? Saludos!
