### ISSUE TITLE
AppDrawer Component modified the prop 'showDrawer'

### ISSUE THREAD

**Issue by KyleRicardo** [tookit/vue-material-admin#58]
The [demo website](http://vma.isocked.com/#/dashboard) just works fine. But when I read the source code and run `yarn serve` locally, there is error.

From the source code I can see that the component `AppDrawer` has a prop named `showDrawer`, which gets value from its parent component `DefaultLayout` and change the visibility of the drawer when the toolbar icon is clicked.  But when the device width is **not enough**, drawer shows as a layout and covers the toolbar icon, the drawer can only be closed by clicking the area out of the drawer. In this case, the prop `showDrawer` is changed by `AppDrawer` itself and the parent component `DefaultLayout` doesn't aware of this at all.

Thus the result is that there are Vue Warning errors in console and the next time you want to open the drawer, you must click the toolbar icon twice because the variable `showDrawer` must change from `true` to `false` and then to `true` again.

What confuses me most is the Internet website works just fine but localhost don't. What can be sure is the usage of prop `showDrawer` is wrong. Any good idea solving it?

I'll update if i get any good idea about this.

**Comment by BenRichter** [comment]
Seems to be fixed in dev Branch
[skip ci] fixed menu issue	286bb80	tookit <wangqiangshen@gmail.com>	2. Sep 2019 at 14:18
