### ISSUE TITLE
Where is the fully version of Vue Material Admin Template?

### ISSUE THREAD

**Issue by SASFMONTOYA** [tookit/vue-material-admin#62]
Good day for you,

I write to you with a question, I saw your template Vue Material Admin, but when I download your Project from GitHub, I see that the version http://vma.isocked.com/ is different than I downloaded, the question is, where is the version that you published? or what’s the difference with the Github Project version?

Thanks,

**Comment by myextend** [comment]
Hi,
I have the same question. The new template version does not contain all ui elements

**Comment by Janloong-Doo** [comment]
+1

**Comment by AlvaroBrasilia** [comment]
+1

**Comment by xbility** [comment]
https://github.com/moeddami/nuxt-material-admin

**Comment by H-pun** [comment]
+1
