### ISSUE TITLE
How should I use this global snackbar 

### ISSUE THREAD

**Issue by ZhaoQi99** [tookit/vue-material-admin#66]
https://github.com/tookit/vue-material-admin/blob/c87cf35f1388c4ef811cc4e2b752d409dbcbcc7a/src/App.vue#L13

**Comment by tookit** [comment]
you can can add a events listener on App.vue, such as
this.$on("SHOW_SNACKBAR",() => {})
then fire the event when ever you want

**Comment by ZhaoQi99** [comment]
> you can can add a events listener on App.vue, such as
> this.$on("SHOW_SNACKBAR",() => {})
> then fire the event when ever you want

Yeap,do you meant that  then I can fire the event using `this.$emit('SHOW_SNACKBAR', args)`??

**Comment by tookit** [comment]
yes
