### ISSUE TITLE
Dark theme: menu onhover should change text color to dark

### ISSUE THREAD

**Issue by dostertag** [tookit/vue-material-admin#7]
I realize this is a project showcasing your work.  It also functions as a 'major' help to the part of the community that is learning (which I'm a part of).  Thank you for posting this repo.  I'm gaining a lot from looking through!!!

TLDR: When hovering over a menu selection while in 'Dark' mode, text is extremely hard to read.  Needs to be a different color, or match the background of the menu.

**Comment by tookit** [comment]
thx, i will double check that.

**Comment by magdoss** [comment]
is there any solution for this issue ?
