### ISSUE TITLE
Passing the parameters doesn't work in breadcrumbs

### ISSUE THREAD

**Issue by GlobalKhabr** [tookit/vue-material-admin#79]
Hi there. Why doesn't passing parameters to the Breadcrumbs menu work?
![Screenshot_1](https://user-images.githubusercontent.com/28756181/110664701-b1bffb00-81d8-11eb-99aa-e0703eee7619.png)

**Comment by tookit** [comment]
it's vue routee issue, you need make your `props: true`, check here [https://router.vuejs.org/guide/essentials/passing-props.html#boolean-mode](url)

**Comment by GlobalKhabr** [comment]
Yup thank you. Update the discord link in Readme.md =)
