### ISSUE TITLE
Demo http://vma.isocked.com/

### ISSUE THREAD

**Issue by ambrosiora** [tookit/vue-material-admin#82]
Hi!

Apparently the demo page [http://vma.isocked.com/](http://vma.isocked.com/) is not working.
It gets stuck on login page.

**Comment by hudsonreis81** [comment]
I did try to show demo page for a work partner but does not work.

**Comment by tookit** [comment]
sorry , the demo api is down, my demo api server is expired.

**Comment by gintsgints** [comment]
Demo works. Imho this should be closed?

**Comment by ambrosiora** [comment]
Yes, at the time the demo was not working.
Now it is, issue closed.
Thanks!
