### ISSUE TITLE
nuxtjs

### ISSUE THREAD

**Issue by ramstein74** [tookit/vue-material-admin#9]
Can i challenge you to convert this awesome work to nuxtjs?

**Comment by TAnas0** [comment]
That would be perfect!

Or just providing clearer guidelines (from you and the author) to convert this to NuxtJs so that it is more appealing to other contributors too.

I am still a novice in Nuxt, so I am not promising anything.

Thanks

**Comment by tookit** [comment]
@ramstein74 please suit your self

**Comment by ramstein74** [comment]
For now i´m just studying your template.
Where ca i get more info about echarts and vue?
Its not clear from here https://github.com/ecomfe/vue-echarts how to use it.
Also you seem to import a different code using import EChart from
'@/components/chart/echart

regards

2018-07-16 20:54 GMT+01:00 Anas TIOUR <notifications@github.com>:
